import type { LiquidationInput } from "@/modules/pricing";

/**
 * Escenario base: un BYD Seal comprado en China, 3 unidades por contenedor,
 * entrando por Buenaventura. Las cifras salen de docs/SEED-DATA.md.
 */
export function baseInput(overrides: Partial<LiquidationInput> = {}): LiquidationInput {
  return {
    vehicle: {
      hsCode: "8703801000",
      powertrain: "BEV",
      originCountry: "CN",
      shipFromCountry: "CN",
      modelYear: 2026,
      hasOriginCertificate: false,
      weightKg: 2185,
      cbm: 14.2,
    },
    origin: {
      purchasePriceUsd: 32_000,
      auctionFeeUsd: 0,
      buyerFeeUsd: 800,
      inlandFreightUsd: 450,
      exportDocsUsd: 320,
      otherUsd: 0,
    },
    freight: {
      containerCostUsd: 8_190,
      surchargesUsd: 980,
      insuranceRate: 0.012,
      insuranceMinimumUsd: 150,
      insuredValueUplift: 0.1,
      transitDays: 36,
      quotedDaysAgo: 4,
      staleAfterDays: 21,
    },
    consolidation: {
      units: [
        { reference: "BYD Seal", fobUsd: 33_570, weightKg: 2185, cbm: 14.2 },
        { reference: "BYD Song Plus", fobUsd: 27_500, weightKg: 1950, cbm: 15.8 },
        { reference: "Zeekr X", fobUsd: 29_000, weightKg: 1965, cbm: 13.4 },
      ],
      commercialMethod: "BY_CIF_VALUE",
      taxableBaseMethod: "BY_FOB_VALUE",
    },
    tariff: {
      ruleId: "rule-bev",
      dutyRate: 0,
      vatRate: 0.05,
      exciseRate: 0,
      dutyBase: "CIF",
      vatBase: "CIF_PLUS_ARANCEL",
      exciseBase: "TOTAL_VALUE_EXCL_IVA",
      exciseThresholdFobUsd: 30_000,
      exciseRateAboveThreshold: 0.16,
      exciseAppliesOnImport: false,
      requiresOriginCertificate: false,
      legalBasis: "Arancel 0% · IVA 5% ET art. 468-1 · INC excluido ET art. 512-5 num. 8",
      confidence: "VERIFIED",
      status: "VALOR",
    },
    destination: [
      {
        code: "PORT_UIP_BUN",
        labelKey: "DESTINATION.PORT",
        method: "PER_VEHICLE",
        currency: "USD",
        amount: 75,
        inExciseBase: true,
        confidence: "VERIFIED",
        legalBasis: "Tarifario SPRBUN vig. 05-ene-2026",
      },
      {
        code: "STORAGE_BUN",
        labelKey: "DESTINATION.STORAGE",
        method: "PER_DAY",
        currency: "USD",
        amount: 8,
        inExciseBase: true,
        confidence: "VERIFIED",
      },
      {
        code: "BROKERAGE",
        labelKey: "DESTINATION.BROKERAGE",
        method: "PERCENT_OF_CIF",
        currency: "COP",
        amount: 0,
        rate: 0.007,
        minimum: 1_500_000,
        inExciseBase: true,
        confidence: "VERIFIED",
      },
      {
        code: "PLATES_BOGOTA",
        labelKey: "DESTINATION.PERMITS",
        method: "PER_VEHICLE",
        currency: "COP",
        amount: 730_700,
        inExciseBase: false,
        confidence: "VERIFIED",
      },
    ],
    addOns: [],
    commercial: {
      marginRate: 0.12,
      serviceFeeCop: 2_500_000,
      paymentProcessingRate: 0.0265,
      depositCop: 20_000_000,
      gmfRate: 0.004,
    },
    fx: {
      trmCommercial: 3_126.08,
      trmFiscal: 3_126.08,
      trmDate: "2026-09-05",
      trmSource: "AUTO",
      trmAgeDays: 0,
    },
    switches: {
      importerIsEndConsumer: true,
      portDays: 6,
    },
    timeline: {
      sourcingDays: 5,
      inlandOriginDays: 7,
      oceanDays: 36,
      portReleaseDays: 10,
      nationalizationDays: 18,
      registrationDays: 10,
    },
    ...overrides,
  };
}
